### ISSUE TITLE
configuration in database

### ISSUE THREAD

**Issue by nil0bject** [freibuis/simple_features#1]
allow configuration/features to be stored in a db table and applied without server restart

**Comment by freibuis** [comment]
🤔 let me think about it.... this should be simple... could this be done and keep it simple? 
if so... how would we work it with rails and non rails apps..... as it is supposed to be simple.

should I try some logic like

rough idea
```ruby
if simple_storage == :db
  if defined? Rails
    #  Active::record lookup
  else 
    # custom database lookup (or redis style key/pair systems)
  end
end
```

config file changed to:
```yaml

environment:
  production:
    storage: db #
    storage_table_name: simple_storage 
  development:
    storage: file # 
    features:
      feature_one: true
      feature_two: false
```
with the table that would store the values in .. I would think creating another gem called simple_storage that would only hold id: key: pair: simple_storage_type example  *maybe I should call it simple_configs :) keeping with the naming convention ;)

```json
{
  id: 1 , 
  key: 'feature_one', 
  value: true, 
  simple_storage_type: :simple_features 
}
```

really open to this idea.. would love opinions how to approach this and keep it simple from the user perspective. (Simple usage as possible with
